### ISSUE TITLE
订阅房间时报错

### ISSUE THREAD

**Issue by Tukimi777** [eric2788/ddstats_client#3]
2023/05/02 00:04:15 [Recovery] 2023/05/02 - 00:04:15 panic recovered:
GET /roomName/27062023 HTTP/1.1
Host: 192.168.3.250:9090
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: b-user-id=4a10ae37-94ba-ae22-c260-f3ae083f059f
Referer: http://192.168.3.250:9090/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

runtime error: invalid memory address or nil pointer dereference
C:/hostedtoolcache/windows/go/1.18.9/x64/src/runtime/panic.go:220 (0x44a115)
C:/hostedtoolcache/windows/go/1.18.9/x64/src/runtime/signal_windows.go:255 (0x44a0e5)
C:/hostedtoolcache/windows/go/1.18.9/x64/src/encoding/json/stream.go:165 (0x516577)
C:/hostedtoolcache/windows/go/1.18.9/x64/src/encoding/json/stream.go:140 (0x51619a)
C:/hostedtoolcache/windows/go/1.18.9/x64/src/encoding/json/stream.go:63 (0x515ed7)
D:/a/ddstats_client/ddstats_client/blive/api.go:50 (0x916b84)
D:/a/ddstats_client/ddstats_client/blive/api.go:12 (0x91645d)
D:/a/ddstats_client/ddstats_client/blive/api.go:54 (0x916d78)
D:/a/ddstats_client/ddstats_client/main.go:62 (0x919a19)
C:/Users/runneradmin/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x8e85a1)
C:/Users/runneradmin/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x8e858c)
C:/Users/runneradmin/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x8e76c6)
C:/Users/runneradmin/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241 (0x8e76a9)
C:/Users/runneradmin/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x8e67d0)
C:/Users/runneradmin/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x8e6438)
C:/Users/runneradmin/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x8e5f71)
C:/hostedtoolcache/windows/go/1.18.9/x64/src/net/http/server.go:2916 (0x6bf07a)
C:/hostedtoolcache/windows/go/1.18.9/x64/src/net/http/server.go:1966 (0x6ba076)
C:/hostedtoolcache/windows/go/1.18.9/x64/src/runtime/asm_amd64.s:1571 (0x464440)

网页端显示   订阅房间失败: Unexpected end of JSON input 
这个是什么问题？

**Comment by eric2788** [comment]
B站API抽風了，返回了無效的格式導致解釋失敗

**Comment by eric2788** [comment]
原來是打錯了一些東西導致nil reference，已更新
